# Generated by Django 4.2.7 on 2023-11-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to=''),
        ),
    ]
