# Generated by Django 4.2.7 on 2023-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_temperaturemeasurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
